# Resumenes mensuales de lluvia y temperaturas

El ejericio consiste en realizar una base de datos utilizando el material de la comisión nacional del agua empleando las herramientas que nos da la libreria pandas. Realizaremos una base de datos para la temperatura y otra para las lluvias.

In [2]:
import pandas as pd
import numpy as np

## Temperaturas

Se utilizarán los datos de temperaturas de la conagua de enero de 2020

In [24]:
T_max = pd.read_csv('T_Max.csv', encoding='latin-1')
T_med = pd.read_csv('T_Med.csv', encoding='latin-1')
T_min = pd.read_csv('T_Min.csv', encoding='latin-1')

In [26]:
pd.merge(pd.merge(T_med, T_min),T_max)

,Lon,Lat,Clave,Edo,Est,Tmed,Tmin,Tmax
0,-102.37,21.78,NGRAG,AGS,El Niagara Ags.,14.225806,5.112903,24.306452
1,-102.79,21.81,MNLAG,AGS,Media Luna Ags.,14.825806,4.838710,25.516129
2,-102.71,21.85,CALVILLO,AGS,Calvillo Ags. SMN*,15.572581,5.470968,26.522581
3,-102.29,21.85,OBSAG,AGS,Observatorio de Aguascalientes Ags.,15.151667,6.946667,24.077419
4,-102.31,21.90,AGSAG,AGS,Aguascalientes Ags.,15.385484,7.048387,23.467742
...,...,...,...,...,...,...,...,...
579,-103.22,23.18,LREZC,ZAC,Gobernador Leobardo Reynoso Zac.,11.172581,2.032258,21.387097
580,-103.64,23.64,SOMZC,ZAC,Sombrerete Zac.,12.386667,4.276667,22.129032
581,-103.10,23.69,ELCZC,ZAC,El Cazadero Zac.,11.346774,1.629032,22.064516
582,-103.03,23.82,RGRZC,ZAC,Río Grande Zac.,11.150000,1.850000,21.935484
583,-103.50,22.33,STEZC,ZAC,Santa Teresa Zac.,12.830357,4.071429,22.225806

In [29]:
print(len(T_max))
print(len(T_med))
print(len(T_min))

722
1282
1282

Nótese que el dataFrame de la temperatura máxima tiene menos elemenos que los dataframes de la temperatura media y mínima, que tienen la misma cantidad de datos, por lo que cuando hacemos merge encontramos la intersección entre media, mínima y máxima, y el dataFrame final tiene menos elemenos que si hacemos merge entre minima y media, que es ideal, pues tiene el mismo número de elementos que media y mínima individualmente.

In [27]:
pd.merge(T_med, T_min)

,Lon,Lat,Clave,Edo,Est,Tmed,Tmin
0,-102.37,21.78,NGRAG,AGS,El Niagara Ags.,14.225806,5.112903
1,-102.79,21.81,MNLAG,AGS,Media Luna Ags.,14.825806,4.838710
2,-102.71,21.85,CALVILLO,AGS,Calvillo Ags. SMN*,15.572581,5.470968
3,-102.29,21.85,OBSAG,AGS,Observatorio de Aguascalientes Ags.,15.151667,6.946667
4,-102.31,21.90,AGSAG,AGS,Aguascalientes Ags.,15.385484,7.048387
...,...,...,...,...,...,...,...
1277,-102.25,22.44,LMOZC,ZAC,Luis Moya Zac.,12.446429,3.214286
1278,-102.46,22.49,GRCZC,ZAC,Genaro Codina Zac.,10.005000,0.500000
1279,-103.60,22.69,LAFLORIDA,ZAC,La Florida Zac. SMN*,12.213462,1.357692
1280,-102.57,22.78,ZACATECASob,ZAC,Observatorio de Zacatecas Zac. SMN*,10.321429,6.423810
1281,-102.27,22.58,OCAZC,ZAC,Ojo Caliente Zac.,8.686364,2.800000

## Lluvias

Para la base de datos de las lluvias se utilizarán los datos de la conagua de los años 2018, 2019 y 2020 del mes de enero

In [73]:
l_2018 = pd.read_csv('Lluvias2018.csv', encoding='latin-1')
l_2019 = pd.read_csv('Lluvias2019.csv', encoding='latin-1')
l_2020 = pd.read_csv('Lluvias2020.csv', encoding='latin-1')

La última columna del DataFrame marca el volumen de lluvias del mes de enero; en cada uno de los datos de 2018, 2019 y 2020 esta columna tiene el mismo nombre, por lo que cuando hacemos un merge, no tenemos el resultado esperado. Además, en el caso del año 2018, en lugar de que la columna de la entidad federativa diga 'EDO' la columna dice 'ESTADO'.
Tenemos que renombrar las columnas.

In [75]:
l_2018.rename(columns={'ENE':'ENE2018', 'ESTADO':'EDO'}, inplace=True)
l_2019.rename(columns={'ENE':'ENE2019'}, inplace=True)
l_2020.rename(columns={'ENE':'ENE2020'}, inplace=True)

Ahora, cuando hacemos merge, la base de datos nos mostrará los resultados de la última columna separados.

In [76]:
pd.merge((pd.merge(l_2018, l_2019)),l_2020)

,LON,LAT,EDO,CLAVE_SIH,NOMBRE,ENE2018,ENE2019,ENE2020
0,-102.309722,21.895000,AGS,AGSAG,"Aguascalientes, Ags.",25.8,6.61,6.61
1,-102.466944,22.188611,AGS,ANVAG,"Cincuenta Aniversario, Ags.",58.6,10.60,10.60
2,-102.712222,21.849167,AGS,CALVILLO,"Calvillo, Ags. SMN*",56.0,18.17,18.17
3,-102.676944,21.997500,AGS,CDRAG,"La Codorniz, Ags.",50.0,16.70,16.70
4,-102.197222,22.007222,AGS,CHOAG,"Cañada Honda, Ags.",17.2,17.30,17.30
...,...,...,...,...,...,...,...,...
752,-103.108889,22.923611,ZAC,STRZC,"Santa Rosa, Zac.",25.5,18.52,18.52
753,-103.879722,23.471944,ZAC,TCHZC,"Chalchihuites, Zac.",6.0,3.00,3.00
754,-103.461944,21.468611,ZAC,TGOZC,"Teúl de González Ortega, Zac.",24.6,30.10,30.10
755,-102.786389,21.560556,ZAC,TLAZC,"Tlalchichila, Zac.",40.7,25.01,25.01
756,-102.576667,22.761389,ZAC,ZACZC,"Zacatecas, Zac.",43.3,12.02,12.02